import { execFileSync, spawn, type ChildProcess } from "node:child_process";
import { createRequire } from "node:module";
import { EventEmitter } from "node:events";
import fs from "node:fs";
import path from "node:path";
import { AbortedError, abortError, log, stripAnsi } from "./util.js";

interface PtyLike {
  write(data: string): void;
  resize(cols: number, rows: number): void;
  kill(): void;
  onData(cb: (d: string) => void): void;
  onExit(cb: (code: number) => void): void;
  pid: number;
}

export interface ShellResult {
  output: string;
  exit_code: number | null;
  timed_out: boolean;
}

const START = "\x1b]777;fam;start\x07";
const EXIT_RE = /\x1b\]777;fam;exit;(\d+)\x07/;
const MARKERS_RE = /\x1b\]777;fam;[^\x07]*\x07/g;
const MAX_OUTPUT = 30_000;

const RCFILE = `# familiar terminal (generated by agentd)
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
export PATH="$HOME/opt/bin:$HOME/.local/bin:$PATH"
export PS1='\\[\\e[1;32m\\]\${FAMILIAR_MACHINE_NAME:-familiar}\\[\\e[0m\\]:\\[\\e[1;34m\\]\\w\\[\\e[0m\\]\\$ '
PS0='\\e]777;fam;start\\a'
__fam_prompt() { local s=$?; printf '\\e]777;fam;exit;%s\\a' "$s"; return $s; }
PROMPT_COMMAND=__fam_prompt
HISTFILE="$HOME/.familiar/bash_history"
bind 'set bell-style none' 2>/dev/null
bind 'set enable-active-region off' 2>/dev/null
`;

/**
 * The newest bash we can find. macOS ships bash 3.2, which has no PS0 and no bracketed paste,
 * so a Homebrew bash is preferred and 3.2 gets a compatible mode (see runLocked).
 */
function findBash(): { bin: string; modern: boolean } {
  const candidates = [process.env.FAMILIAR_BASH, "/opt/homebrew/bin/bash", "/usr/local/bin/bash", "bash"].filter((c): c is string => !!c);
  let fallback: { bin: string; modern: boolean } | null = null;
  for (const bin of candidates) {
    if (bin.includes("/") && !fs.existsSync(bin)) continue;
    try {
      const [maj, min] = execFileSync(bin, ["-c", 'echo "${BASH_VERSINFO[0]} ${BASH_VERSINFO[1]}"'], { encoding: "utf8" }).trim().split(" ").map(Number);
      const modern = maj > 4 || (maj === 4 && min >= 4);
      if (modern) return { bin, modern };
      fallback ??= { bin, modern };
    } catch {
      /* not runnable */
    }
  }
  return fallback ?? { bin: "bash", modern: true };
}

/** npm installs node-pty's macOS spawn-helper without its exec bit, which makes every spawn fail with posix_spawnp. */
function fixSpawnHelper() {
  try {
    const dir = path.dirname(createRequire(import.meta.url).resolve("node-pty/package.json"));
    for (const sub of ["prebuilds/darwin-arm64", "prebuilds/darwin-x64", "build/Release"]) {
      const helper = path.join(dir, sub, "spawn-helper");
      if (fs.existsSync(helper) && !(fs.statSync(helper).mode & 0o111)) fs.chmodSync(helper, 0o755);
    }
  } catch {
    /* node-pty not installed */
  }
}

/**
 * One visible bash shell per machine. Everything the agent runs is typed into it, so the viewer sees it.
 * Completion is detected with invisible OSC markers emitted from PS0 (command start) and PROMPT_COMMAND (exit code).
 */
export class Terminal extends EventEmitter {
  private pty: PtyLike | null = null;
  private outputs: Array<(d: string) => void> = [];
  private hold = "";
  private readyPromise: Promise<void> | null = null;
  private lock: Promise<unknown> = Promise.resolve();
  mode = "none";
  private stopped = false;
  cols = 120;
  rows = 32;
  private bash = findBash();
  private startedAt = 0;
  private quickExits = 0;

  constructor(
    private home: string,
    private machineName: string,
  ) {
    super();
  }

  private starting: Promise<void> | null = null;

  /** Start the shell, or wait for the one already starting. Never spawns a second shell over a live one. */
  start(): Promise<void> {
    if (this.pty) return this.readyPromise ?? Promise.resolve();
    this.starting ??= this.spawnShell().finally(() => (this.starting = null));
    return this.starting;
  }

  private async spawnShell(): Promise<void> {
    const rc = path.join(this.home, ".familiar", "bashrc");
    fs.mkdirSync(path.dirname(rc), { recursive: true });
    fs.writeFileSync(rc, RCFILE);
    const env: Record<string, string> = {};
    for (const [k, v] of Object.entries(process.env)) {
      if (v === undefined || /^FAMILIAR_(MACHINE_TOKEN|AGENTD_TOKEN)$/.test(k)) continue;
      env[k] = v;
    }
    Object.assign(env, {
      HOME: this.home,
      TERM: "xterm-256color",
      COLORTERM: "truecolor",
      FAMILIAR_MACHINE_NAME: this.machineName,
      LANG: env.LANG || "C.UTF-8",
    });
    const args = ["--rcfile", rc, "-i"];
    if (!this.bash.modern) log("warn", `${this.bash.bin} is older than 4.4; using compatible terminal mode (install a newer bash, e.g. brew install bash, for a nicer terminal)`);
    this.startedAt = Date.now();
    this.pty = (await this.spawnNodePty(args, env)) ?? this.spawnFallback(args, env);
    this.pty.onData((d) => this.onData(d));
    this.pty.onExit((code) => {
      if (this.stopped) return;
      log("warn", `terminal shell exited (${code}); restarting`);
      this.pty = null;
      this.readyPromise = null;
      // Back off when the shell dies straight away, so a broken setup doesn't spin.
      this.quickExits = Date.now() - this.startedAt < 5000 ? this.quickExits + 1 : 0;
      const delay = Math.min(1000 * 2 ** this.quickExits, 60_000);
      setTimeout(() => this.stopped || this.start().catch((e) => log("error", "terminal restart failed", e)), delay);
    });
    this.readyPromise = new Promise<void>((resolve) => {
      const t = setTimeout(() => {
        log("warn", "terminal did not report a prompt in 10s; continuing");
        resolve();
      }, 10_000);
      const l = (d: string) => {
        if (EXIT_RE.test(d)) {
          clearTimeout(t);
          this.off("raw", l);
          resolve();
        }
      };
      this.on("raw", l);
    });
    await this.readyPromise;
    log("info", `terminal ready (${this.mode})`);
  }

  private async spawnNodePty(args: string[], env: Record<string, string>): Promise<PtyLike | null> {
    if (process.env.FAMILIAR_NO_NODE_PTY) return null;
    try {
      fixSpawnHelper();
      const mod: any = await import("node-pty");
      const ptyMod = mod.default ?? mod;
      const p = ptyMod.spawn(this.bash.bin, args, { name: "xterm-256color", cols: this.cols, rows: this.rows, cwd: this.home, env });
      this.mode = "node-pty";
      return {
        pid: p.pid,
        write: (d) => p.write(d),
        resize: (c, r) => p.resize(c, r),
        kill: () => p.kill(),
        onData: (cb) => p.onData(cb),
        onExit: (cb) => p.onExit((e: { exitCode: number }) => cb(e.exitCode)),
      };
    } catch (e) {
      log("warn", `node-pty unavailable (${(e as Error).message}); falling back`);
      return null;
    }
  }

  private spawnFallback(args: string[], env: Record<string, string>): PtyLike {
    const shellCmd = [this.bash.bin, ...args].map((a) => `'${a.replace(/'/g, `'\\''`)}'`).join(" ");
    let child: ChildProcess;
    // macOS's BSD script can't run with a socket for stdin (node's pipes), so there we go straight to python's pty.
    const hasScript = process.platform !== "darwin" && (fs.existsSync("/usr/bin/script") || fs.existsSync("/bin/script"));
    const sizeEnv = { ...env, COLUMNS: String(this.cols), LINES: String(this.rows) };
    const inner = `stty cols ${this.cols} rows ${this.rows} 2>/dev/null; exec ${shellCmd}`;
    if (hasScript) {
      child = spawn("script", ["-qfc", inner, "/dev/null"], { cwd: this.home, env: sizeEnv, stdio: "pipe" });
      this.mode = "script";
    } else {
      const py = `import pty,sys\nsys.exit(pty.spawn(${JSON.stringify([this.bash.bin, ...args])}) >> 8)`;
      child = spawn("python3", ["-c", py], { cwd: this.home, env: sizeEnv, stdio: "pipe" });
      this.mode = "python-pty";
    }
    return {
      pid: child.pid ?? 0,
      write: (d) => child.stdin?.write(d),
      resize: () => {},
      kill: () => child.kill("SIGKILL"),
      onData: (cb) => {
        child.stdout?.setEncoding("utf8");
        child.stderr?.setEncoding("utf8");
        child.stdout?.on("data", cb);
        child.stderr?.on("data", cb);
      },
      onExit: (cb) => child.on("exit", (c) => cb(c ?? -1)),
    };
  }

  private onData(chunk: string) {
    this.emit("raw", chunk);
    // Strip our invisible markers from what viewers see, holding back a possibly split sequence.
    let s = this.hold + chunk;
    this.hold = "";
    const idx = s.lastIndexOf("\x1b]");
    if (idx >= 0 && s.indexOf("\x07", idx) < 0 && s.length - idx < 64) {
      this.hold = s.slice(idx);
      s = s.slice(0, idx);
    }
    s = s.replace(MARKERS_RE, "");
    if (s) for (const l of this.outputs) l(s);
  }

  /** Subscribe to viewer-facing output. */
  onOutput(cb: (d: string) => void) {
    this.outputs.push(cb);
  }

  write(data: string) {
    this.pty?.write(data);
  }

  resize(cols: number, rows: number) {
    this.cols = cols;
    this.rows = rows;
    this.pty?.resize(cols, rows);
  }

  /** Type a command into the visible shell and capture its output and exit code. Commands are serialised. */
  run(command: string, timeoutMs: number, signal?: AbortSignal): Promise<ShellResult> {
    const next = this.lock.then(() => this.runLocked(command, timeoutMs, signal));
    this.lock = next.catch(() => undefined);
    return next;
  }

  private async runLocked(command: string, timeoutMs: number, signal?: AbortSignal): Promise<ShellResult> {
    if (!this.pty) await this.start();
    await this.readyPromise;
    if (signal?.aborted) throw abortError(signal);
    let text = command.replace(/\r\n/g, "\n").trimEnd();
    if (text.includes("\n")) text = `{\n${text}\n}`;
    return new Promise<ShellResult>((resolve, reject) => {
      let buf = "";
      let started = false;
      let timedOut = false;
      let settled = false;
      let killTimer: NodeJS.Timeout | null = null;
      const finish = (exit: number | null, err?: Error) => {
        if (settled) return;
        settled = true;
        this.off("raw", onRaw);
        clearTimeout(timer);
        if (killTimer) clearTimeout(killTimer);
        signal?.removeEventListener("abort", onAbort);
        if (err) return reject(err);
        let out = stripAnsi(buf.replace(MARKERS_RE, "")).replace(/\n+$/, "");
        if (out.length > MAX_OUTPUT) out = "…(truncated)…\n" + out.slice(-MAX_OUTPUT);
        resolve({ output: out, exit_code: exit, timed_out: timedOut });
      };
      const onRaw = (d: string) => {
        let s = d;
        if (!started) {
          const i = s.indexOf(START);
          if (i < 0) return;
          started = true;
          s = s.slice(i + START.length);
        }
        buf += s;
        const m = EXIT_RE.exec(buf);
        if (m) {
          buf = buf.slice(0, m.index);
          finish(Number(m[1]));
        }
      };
      const interrupt = () => {
        this.write("\x03");
        killTimer = setTimeout(() => finish(null), 3000);
      };
      const timer = setTimeout(() => {
        timedOut = true;
        interrupt();
      }, timeoutMs);
      const onAbort = () => {
        this.write("\x03");
        finish(null, signal ? abortError(signal) : new AbortedError("cancelled"));
      };
      signal?.addEventListener("abort", onAbort, { once: true });
      this.on("raw", onRaw);
      // Clear any half-typed line, then paste the command (bracketed paste keeps tabs/newlines literal) and run it.
      this.write("\x05\x15");
      if (this.bash.modern) this.write(`\x1b[200~${text}\x1b[201~\r`);
      // bash < 4.4 has neither PS0 nor bracketed paste: print the start marker ourselves and type the command.
      else this.write(`printf '\\e]777;fam;start\\a'; ${text}\r`);
    });
  }

  kill() {
    this.stopped = true;
    const p = this.pty;
    this.pty = null;
    if (p) {
      try {
        p.kill();
      } catch {
        /* ignore */
      }
    }
    this.removeAllListeners("raw");
  }
}
